version: '3.9'
services:
  postgres:
    container_name: index-postgres
    image: postgres:15.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5435:5432'
